NovaMentoria/Models/BankAccount.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace NovaMentoria.Models
{
    public class BankAccount
    {
        [Key]

        public int Id { get; set; }
        
        public int EnterpriseId { get; set; }
        [DisplayName("Empresa")]
        public Enterprise Enterprise { get; set; }
        [DisplayName("Centro de Custo")]
        public string CostCenter { get; set; }
        
        [DisplayName("Banco")]
        public string Name { get; set; }
        [DisplayName("Saldo Inicial")]
        public float InitialBalance { get; set; }
        [DisplayName("Saldo Atual")]
        public float Balance { get; set; }
        public List<Expensive> Expanses { get;}

        public void AttCalculos()
        {
            this.Balance =
            this.InitialBalance +
            this.Expanses.Where(x => x.Type).Sum(x => x.Value) -
            this.Expanses.Where(x => !x.Type).Sum(x => x.Value);
        }

    }
}

NovaMentoria/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NovaMentoria.Data;
using NovaMentoria.Models;

namespace NovaMentoria.Controllers
{
    public class BankAccountsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BankAccountsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BankAccounts
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 5)
        {
            int totalCount = _context.BankAccount.Count();
            int excludeRecords = (pageNumber - 1) * pageSize;
            var data = await _context.BankAccounts
                .Skip(excludeRecords)
                .Take(pageSize)
                .OrderByDescending(a  => a.Name)
                .Include(b => b.Enterprise)
                .Include(b => b.Expanses)
                .ToListAsync();

            data.ForEach(x => x.AttCalculos());

            var viewModel = new PaginationViewModel<BankAccount>
            {
                Items = data,
                PageNumber = pageNumber,
                PageSize = pageSize,
                TotalCount = totalCount,
            };

            return View(viewModel);

        }
        
        
            

        // GET: BankAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccounts
                .Include(b => b.Enterprise)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // GET: BankAccounts/Create
        public IActionResult Create()
        {
            ViewData["EnterpriseId"] = new SelectList(_context.Enterprise, "Id", "Name");
            return View();
        }

        // POST: BankAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EnterpriseId,CostCenter,Balance,Name,InitialBalance")] BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bankAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnterpriseId"] = new SelectList(_context.Enterprise, "Id", "Name", bankAccount.EnterpriseId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccounts.FindAsync(id);
            if (bankAccount == null)
            {
                return NotFound();
            }
            ViewData["EnterpriseId"] = new SelectList(_context.Enterprise, "Id", "Name", bankAccount.EnterpriseId);
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EnterpriseId,CostCenter,Balance,Name,InitialBalance")] BankAccount bankAccount)
        {
            if (id != bankAccount.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bankAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BankAccountExists(bankAccount.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnterpriseId"] = new SelectList(_context.Enterprise, "Id", "Name", bankAccount.EnterpriseId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccounts
                .Include(b => b.Enterprise)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bankAccount = await _context.BankAccounts.FindAsync(id);
            _context.BankAccounts.Remove(bankAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BankAccountExists(int id)
        {
            return _context.BankAccounts.Any(e => e.Id == id);
        }
    }
}

NovaMentoria/Views/BankAccounts/Create.cshtml
@model NovaMentoria.Models.BankAccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BankAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EnterpriseId" class="control-label"></label>
                <select asp-for="EnterpriseId" class ="form-control" asp-items="ViewBag.EnterpriseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CostCenter" class="control-label"></label>
                <input asp-for="CostCenter" class="form-control" />
                <span asp-validation-for="CostCenter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InitialBalance" class="control-label"></label>
                <input asp-for="InitialBalance" class="form-control" />
                <span asp-validation-for="InitialBalance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NovaMentoria/Views/BankAccounts/Delete.cshtml
@model NovaMentoria.Models.BankAccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Enterprise)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Enterprise.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostCenter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostCenter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialBalance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialBalance)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NovaMentoria/Views/BankAccounts/Details.cshtml
@model NovaMentoria.Models.BankAccount

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Enterprise)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Enterprise.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostCenter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostCenter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialBalance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialBalance)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NovaMentoria/Views/BankAccounts/Edit.cshtml
@model NovaMentoria.Models.BankAccount

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BankAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EnterpriseId" class="control-label"></label>
                <select asp-for="EnterpriseId" class="form-control" asp-items="ViewBag.EnterpriseId"></select>
                <span asp-validation-for="EnterpriseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostCenter" class="control-label"></label>
                <input asp-for="CostCenter" class="form-control" />
                <span asp-validation-for="CostCenter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InitialBalance" class="control-label"></label>
                <input asp-for="InitialBalance" class="form-control" />
                <span asp-validation-for="InitialBalance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NovaMentoria/Views/BankAccounts/Index.cshtml
@model PaginationViewModel<BankAccount>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Enterprise)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().CostCenter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().InitialBalance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Balance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Items) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Enterprise.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostCenter)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InitialBalance)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Balance)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<partial name="_paginator" />

@section Scripts
    {
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

<script>
    $(document).ready(function () {
        $("#checkCentral").click(function () {
            //Verifica se o botão que possui o id checkCentral foi pressionado
            //Encontra todas as tags input que possuem a propriedade name = checkSelect
            //Troca a propriedade checked pelo valor que o botão id checkCentral possui
            $("input[name='checkSelect']").prop('checked', $(this).prop('checked'));
            if ($(this).prop('checked'))
                $("#botaoDeletar").show();
            else
                $("#botaoDeletar").hide();
        });

        $("input[name='checkSelect']").click(function () {
            if ($(this).prop('checked')) {
                $("#botaoDeletar").show();
            }
            else {
                $("#botaoDeletar").hide();
            }
        });

        $("input[name='checkSelect']").click(function () {
            var IdSelecionados = $("input[name='checkSelect']:checked").length;

            if ($(this).is(':checked') || IdSelecionados > 0) {
                $("#botaoDeletar").show();
            }
            else {
                $("#botaoDeletar").hide();
                $("#checkCentral").prop('checked', false);
            }

        });

        $("#botaoDeletar").click(function () {
            var idsSelecionados = $("input[name='checkSelect']:checked").map(function () {
                return $(this).val();
            }).get();
            //Map: é como um foreach para arrays
            //Gera uma informação nova

            //Via HTML
            if (idsSelecionados.length > 0) {
                if (confirm("Você tem certeza de que deseja deletar este(s) registro(s)?")) {
                    $.ajax({
                        url: '@Url.Action("MultipleDelete", "BankAccounts")',
                        type: 'POST',
                        data: { ids: idsSelecionados }, //Passa na URl as informações
                        success: function () {
                            location.reload()
                        },
                        error: function () {
                            alert("Um erro ocorreu ao tentar deletar estes(s) registro(s).")
                        }
                    });
                }
            }
            else {
                alert("Por favor, selecione pelo menos um item para ser deletado")
            }
        });
    });
</script>
}